//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Randomizer.Framework.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Randomizer.Framework.Services.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizer.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an item....
        /// </summary>
        public static string EnterAnItemPlaceholder {
            get {
                return ResourceManager.GetString("EnterAnItemPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your list&apos;s name....
        /// </summary>
        public static string EnterListNamePlaceholder {
            get {
                return ResourceManager.GetString("EnterListNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding this item :( Please, try again!.
        /// </summary>
        public static string ErrorAddingItem {
            get {
                return ResourceManager.GetString("ErrorAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature hasn&apos;t been implemented yet. Try again later!.
        /// </summary>
        public static string FeatureNotImplementedMessage {
            get {
                return ResourceManager.GetString("FeatureNotImplementedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same ID already exists!.
        /// </summary>
        public static string ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item couldn&apos;t be deleted :( Please, try again!.
        /// </summary>
        public static string ItemNotDeleted {
            get {
                return ResourceManager.GetString("ItemNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item couldn&apos;t be updated :( Please, try again!.
        /// </summary>
        public static string ItemNotUpdated {
            get {
                return ResourceManager.GetString("ItemNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list couldn&apos;t be cleared :( Please, try again!.
        /// </summary>
        public static string ListNotCleared {
            get {
                return ResourceManager.GetString("ListNotCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List.
        /// </summary>
        public static string NewListPageTitle {
            get {
                return ResourceManager.GetString("NewListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here....
        /// </summary>
        public static string NothingHereLabel {
            get {
                return ResourceManager.GetString("NothingHereLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKMessage {
            get {
                return ResourceManager.GetString("OKMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string OopsMessage {
            get {
                return ResourceManager.GetString("OopsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize!.
        /// </summary>
        public static string RandomizeLabel {
            get {
                return ResourceManager.GetString("RandomizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Lists.
        /// </summary>
        public static string YourListsLabel {
            get {
                return ResourceManager.GetString("YourListsLabel", resourceCulture);
            }
        }
    }
}
