before_script:
  - nuget restore
  - dotnet restore
  - MSBuild .\Randomizer.sln /t:restore

build:
  stage: build
  script:
    - MSBuild Randomizer.sln -p:Configuration=Debug
    - MSBuild Randomizer.sln -p:Configuration=Release