before_script:
  windows_path:
  - nuget restore
  - dotnet restore

build:
  stage: build
  script:
    - MSBuild Randomizer.sln -p:Configuration=Debug
    - MSBuild Randomizer.sln -p:Configuration=Release