stages:
  - build
  - DeployAndroid
  - DeployiOS

before_script:
  - nuget restore
  - dotnet restore
  - MSBuild Randomizer.sln /t:restore
  
build:
  stage: build
  script:
    - MSBuild Randomizer.sln /p:ServerAddress=%MAC_ADDRESS% /p:ServerUser=%MAC_USER% /p:ServerPassword=%MAC_PASS% -p:Configuration=Debug 
    
deployandroid:
  stage: DeployAndroid
  script:
    - MSBuild /t:Clean /p:Configuration=Release
    - MSBuild /p:Configuration=Release /t:SignAndroidPackage .\Randomizer\Randomizer.Android\Randomizer.Android.csproj
    - curl -X POST "https://api.appcenter.ms/v0.1/apps/juansero29/%ANDROID_APP_NAME%/release_uploads" -H "accept:application/json" -H "X-API-Token:%APP_CENTER_TOKEN% " -H "Content-Type:application/json" -d "{ \"release_id\":0}" > json
    - for /f "tokens=*" %%t in ('type json ^| jq -r .upload_url') do set upload_url=%%t
    - for /f "tokens=*" %%t in ('type json ^| jq -r .upload_id') do set upload_id=%%t
    - curl -F "ipa=@.\Randomizer\Randomizer.Android\bin\Release\fr.ClubInfo.Randomizer-Signed.apk" %upload_url%
    - curl -X PATCH --header "Content-Type:application/json" --header "Accept:application/json" --header "X-API-Token:%APP_CENTER_TOKEN%" -d "{ \"status\":\"committed\"  }" "https://api.appcenter.ms/v0.1/apps/juansero29/%ANDROID_APP_NAME%/release_uploads/%upload_id%" > json2
    - for /f "tokens=*" %%t in ('type json2 ^| jq -r .release_id') do set release_id=%%t
    - for /f "tokens=*" %%t in ('type json2 ^| jq -r .release_url') do set release_url=%%t
    - curl -X PATCH --header "Content-Type:application/json" --header "Accept:application/json" --header "X-API-Token:%APP_CENTER_TOKEN%" -d "{ \"destination_name\":\"Testers\", \"release_notes\":\"%CI_COMMIT_MESSAGE%\" }" "https://api.appcenter.ms/%release_url%"
    - del "C:\Windows\System32\config\systemprofile\AppData\Local\Xamarin\Mono for Android\debug.keystore"

  environment:
    name: App Center Deployment - Android
    url: https://appcenter.ms/users/juansero29/apps/Randomizer-1/distribute/releases/
    
deployios:
  stage: DeployiOS
  script:
    - MSBuild Randomizer.sln /p:ServerAddress=%MAC_ADRESS% /p:ServerUser=%MAC_USER% /p:ServerPassword=%MAC_PASS% -p:Configuration=Release /p:IpaPackageDir="./ipa"
    - curl -X POST "https://api.appcenter.ms/v0.1/apps/juansero29/%IOS_APP_NAME%/release_uploads" -H "accept:application/json" -H "X-API-Token:%APP_CENTER_TOKEN%" -H "Content-Type:application/json" -d "{ \"release_id\":0}" > json
    - for /f "tokens=*" %%t in ('type json ^| jq -r .upload_url') do set upload_url=%%t
    - for /f "tokens=*" %%t in ('type json ^| jq -r .upload_id') do set upload_id=%%t
    - curl -F "ipa=@.\Randomizer\Randomizer.iOS\ipa\Randomizer.iOS.ipa" %upload_url%
    - curl -X PATCH --header "Content-Type:application/json" --header "Accept:application/json" --header "X-API-Token:%APP_CENTER_TOKEN%" -d "{ \"status\":\"committed\"  }" "https://api.appcenter.ms/v0.1/apps/juansero29/%IOS_APP_NAME%/release_uploads/%upload_id%" > json2
    - for /f "tokens=*" %%t in ('type json2 ^| jq -r .release_id') do set release_id=%%t
    - for /f "tokens=*" %%t in ('type json2 ^| jq -r .release_url') do set release_url=%%t
    - curl -X PATCH --header "Content-Type:application/json" --header "Accept:application/json" --header "X-API-Token:%APP_CENTER_TOKEN%" -d "{ \"destination_name\":\"Testers\", \"release_notes\":\"%CI_COMMIT_MESSAGE%" }" "https://api.appcenter.ms/%release_url%"
  environment:
    name: App Center Deployment - iOS
    url: https://appcenter.ms/users/juansero29/apps/Randomizer/distribute/releases/
