stages:
  - build
  - deploy

before_script:
  - echo %MAC_ADRESS%
  - echo "%MAC_ADRESS"
  - echo $env:MAC_ADRESS
  - echo "$env:MAC_ADRESS"
  - nuget restore
  - dotnet restore


build:
  stage: build
  script:
    - MSBuild Randomizer.sln /t:restore
    - MSBuild Randomizer.sln /p:ServerAddress="%MAC_ADRESS%" /p:ServerUser="%MAC_USER%" /p:ServerPassword="%MAC_PASS%" -p:Configuration=Debug 
    - MSBuild Randomizer.sln /p:ServerAddress="%MAC_ADRESS%" /p:ServerUser="%MAC_USER%" /p:ServerPassword="%MAC_PASS%" -p:Configuration=Release
deploy:
  stage: deploy
  script:
    - echo "deploying..."
  environment:
    name: staging
    url: https://staging.example.com

