stages:
  - build
  - deployandroid
  - deployios

before_script:
  - nuget restore
  - dotnet restore
  - MSBuild Randomizer.sln /t:restore
  - curl -X POST "https://api.appcenter.ms/v0.1/apps/juansero29/%ANDROID_APP_NAME%/release_uploads" -H "accept&#58;application/json" -H "X-API-Token:%APP_CENTER_TOKEN% " -H "Content-Type:application/json" -d "{ \"release_id\":0}" > json

build:
  stage: build
  script:
    - MSBuild Randomizer.sln /p:ServerAddress=%MAC_ADDRESS% /p:ServerUser=%MAC_USER% /p:ServerPassword=%MAC_PASS% -p:Configuration=Debug 
    
deployandroid:
  stage: deployandroid
  script:
    - MSBuild /t:Clean /p:Configuration=Release
    - MSBuild /t:SignAndroidPackage /p:Configuration=Release .\Randomizer\Randomizer.Android\Randomizer.Android.csproj
    - curl -X POST "https://api.appcenter.ms/v0.1/apps/juansero29/%ANDROID_APP_NAME%/release_uploads" -H "accept&#58;application/json" -H "X-API-Token:%APP_CENTER_TOKEN% " -H "Content-Type:application/json" -d "{ \"release_id\":0}" > json
    - for /f "tokens=*" %%t in ('type json ^| jq -r .upload_url') do set upload_url=%%t
    - for /f "tokens=*" %%t in ('type json ^| jq -r .upload_id') do set upload_id=%%t
    - curl -F "ipa=@.\Randomizer\Randomizer.Android\bin\Release\fr.ClubInfo.Randomizer-Signed.apk" %upload_url%
    - curl -X PATCH --header "Content-Type:application/json" --header "Accept:application/json" --header "X-API-Token:%APP_CENTER_TOKEN%" -d "{ \"status\":\"committed\"  }" "https://api.appcenter.ms/v0.1/apps/juansero29/%ANDROID_APP_NAME%/release_uploads/%upload_id%" > json2
    - for /f "tokens=*" %%t in ('type json ^| jq -r .release_id') do set release_id=%%t
    - for /f "tokens=*" %%t in ('type json ^| jq -r .release_url') do set release_url=%%t
    - curl -X PATCH --header "Content-Type:application/json" --header "Accept:application/json" --header "X-API-Token:%APP_CENTER_TOKEN%" -d "{ \"destination_name\":\"Testers\", \"release_notes\":\"%CI_COMMIT_MESSAGE%" }" "https://api.appcenter.ms/%release_url%"

  environment:
    name: stagingandroid
    url: https://api.appcenter.ms/%release_url%
    
deployios:
  stage: deployios
  script:
    - MSbuild /p:Configuration="Release" /p:Platform="iPhone" /p:ServerAddress=%MAC_ADDRESS% /p:ServerUser=%MAC_USER% /p:ServerPassword=%MAC_PASS% /p:IpaPackageDir="./ipa" /t:Build Randomizer.sln
    - curl -X POST "https://api.appcenter.ms/v0.1/apps/juansero29/%IOS_APP_NAME%/release_uploads" -H "accept:application/json" -H "X-API-Token:%APP_CENTER_TOKEN%" -H "Content-Type:application/json" -d "{ \"release_id\":0}" > json
    - for /f "tokens=*" %%t in ('type json ^| jq -r .upload_url') do set upload_url=%%t
    - for /f "tokens=*" %%t in ('type json ^| jq -r .upload_id') do set upload_id=%%t
    - curl -F "ipa=@.\Randomizer\Randomizer.iOS\ipa\Randomizer.iOS.ipa" %upload_url%
    - curl -X PATCH --header "Content-Type:application/json" --header "Accept:application/json" --header "X-API-Token:%APP_CENTER_TOKEN%" -d "{ \"status\":\"committed\"  }" "https://api.appcenter.ms/v0.1/apps/juansero29/%IOS_APP_NAME%/release_uploads/%upload_id%" > json2
    - for /f "tokens=*" %%t in ('type json ^| jq -r .release_id') do set release_id=%%t
    - for /f "tokens=*" %%t in ('type json ^| jq -r .release_url') do set release_url=%%t
    - curl -X PATCH --header "Content-Type:application/json" --header "Accept:application/json" --header "X-API-Token:%APP_CENTER_TOKEN%" -d "{ \"destination_name\":\"Testers\", \"release_notes\":\"%CI_COMMIT_MESSAGE%" }" "https://api.appcenter.ms/%release_url%"
  environment:
    name: stagingios
    url: https://api.appcenter.ms/%release_url%
